# Generated by Django 3.2.7 on 2021-11-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo4App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
    ]
